package dev.dizyaa.dizgram.feature.chat.domain

sealed class MessageContent {
    data class Text(val text: String, val webPageUrl: String?) : MessageContent()
    data class Photo(val file: File, val text: String) : MessageContent()
//    data class Audio(val audio: File, val text: String) : MessageContent()
//    data class Document(val document: File, val text: String) : MessageContent()
//    data class Video(val videoUrl: String, val text: String) : MessageContent()
//    data class Animation(val animationUrl: String) : MessageContent()
//    data class Sticker(val stickerUrl: String) : MessageContent()
//    data class ExpiredPhoto(val expiredPhotoUrl: String) : MessageContent()
//    data class ExpiredVideo(val expiredVideoUrl: String) : MessageContent()
//    data class VideoNote(val videoNoteUrl: String) : MessageContent()
//    data class VoiceNote(val voiceNoteUrl: String) : MessageContent()
//    data class Location(val latitude: Double, val longitude: Double) : MessageContent()
//    data class Venue(val venueName: String, val latitude: Double, val longitude: Double) : MessageContent()
//    data class Contact(val contactName: String, val phoneNumber: String) : MessageContent()
//    data class AnimatedEmoji(val emoji: String) : MessageContent()
//    data class Dice(val diceValue: Int) : MessageContent()
//    data class Game(val gameName: String) : MessageContent()
//    data class Poll(val question: String, val options: List<String>) : MessageContent()
//    data class Invoice(val invoiceText: String) : MessageContent()
//    data class Call(val callDescription: String) : MessageContent()
//    data class VideoChatScheduled(val scheduledTime: String) : MessageContent()
//    data class VideoChatStarted(val chatId: Long) : MessageContent()
//    data class VideoChatEnded(val chatId: Long) : MessageContent()
//    data class InviteVideoChatParticipants(val invitees: List<String>) : MessageContent()
//    data class BasicGroupChatCreate(val groupName: String) : MessageContent()
//    data class SupergroupChatCreate(val supergroupName: String) : MessageContent()
//    data class ChatChangeTitle(val newTitle: String) : MessageContent()
//    data class ChatChangePhoto(val newPhotoUrl: String) : MessageContent()
//    object ChatDeletePhoto : MessageContent()
//    data class ChatAddMembers(val members: List<String>) : MessageContent()
//    data class ChatJoinByLink(val link: String) : MessageContent()
//    data class ChatJoinByRequest(val userId: Long) : MessageContent()
//    data class ChatDeleteMember(val userId: Long) : MessageContent()
//    data class ChatUpgradeTo(val supergroupId: Long) : MessageContent()
//    data class ChatUpgradeFrom(val basicGroupId: Long) : MessageContent()
//    data class PinMessage(val pinnedMessage: MessageContent) : MessageContent()
//    data class ScreenshotTaken(val screenshotUrl: String) : MessageContent()
//    data class ChatSetTheme(val theme: String) : MessageContent()
//    data class ChatSetTtl(val ttl: Int) : MessageContent()
//    data class CustomServiceAction(val action: String) : MessageContent()
//    data class GameScore(val game: String, val score: Int) : MessageContent()
//    data class PaymentSuccessful(val amount: Double, val currency: String) : MessageContent()
//    data class PaymentSuccessfulBot(val amount: Double, val currency: String, val botName: String) : MessageContent()
//    data class ContactRegistered(val contactName: String) : MessageContent()
//    data class WebsiteConnected(val website: String) : MessageContent()
//    data class PassportDataSent(val data: String) : MessageContent()
//    data class PassportDataReceived(val data: String) : MessageContent()
//    data class ProximityAlertTriggered(val distance: Double) : MessageContent()

    object Unsupported : MessageContent()
}
